services:
  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
  weather-station-server:
    build: weather_station_server
    working_dir: /code
    command: waitress-serve --listen=*:5001 server:app
    volumes:
      - ./weather_station_server:/code
    ports:
      - '5001:5001'
    restart: always
